In [1]:
import pandas as pd

data = pd.read_csv("C:/Users/RUKAUSHI/Angular_Apps/ml/data/all_kindle_review.csv")
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [2]:
df= data[['reviewText','rating']]
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [3]:
df.shape

(12000, 2)

In [4]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [5]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [6]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [7]:
df['rating'] = df['rating'].apply(lambda x:0 if x<3 else 1)

C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\195494786.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x:0 if x<3 else 1)


In [8]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [9]:
df['reviewText']= df['reviewText'].str.lower()

C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\2403061003.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']= df['reviewText'].str.lower()


In [10]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [11]:
import re 
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RUKAUSHI\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [12]:
from bs4 import BeautifulSoup

In [14]:
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords


C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\2419796021.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))


In [15]:
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 


C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\3172975654.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))


In [16]:
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags


C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\2877217561.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))


In [23]:

df['reviewText'] = df['reviewText'].astype(str).apply(
    lambda x: BeautifulSoup(x, 'html.parser').get_text()
)
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))


C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\62972006.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].astype(str).apply(
C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\62972006.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))


In [24]:
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))
df.head()

C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\1944237134.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))


reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [25]:
from nltk.stem import WordNetLemmatizer

In [26]:
lemm = WordNetLemmatizer()

In [27]:
def lemm_words(text):
    return " ".join([lemm.lemmatize(word) for word in text.split()])

In [28]:
df['reviewText'] = df['reviewText'].apply(lambda x: lemm_words(x))

C:\Users\RUKAUSHI\AppData\Local\Temp\ipykernel_20432\1610146101.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x: lemm_words(x))


In [29]:
df.head()

reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [30]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()
x_train_bow = bow.fit_transform(x_train).toarray()
x_test_bow = bow.fit_transform(x_test).toarray()

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x_train_tfidf = tfidf.fit_transform(x_train).toarray()
x_test_tfidf = tfidf.fit_transform(x_test).toarray()

In [33]:
import numpy as np
from gensim.utils import simple_preprocess

In [34]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [35]:

x_train_tokens = [simple_preprocess(doc) for doc in x_train]
x_test_tokens  = [simple_preprocess(doc) for doc in x_test]


In [36]:

DIM = wv.vector_size  # 300 for Google News

def doc_vector_avg(tokens, keyed_vectors, dim):
    vecs = [keyed_vectors[w] for w in tokens if w in keyed_vectors]
    if not vecs:
        return np.zeros(dim, dtype=np.float32)
    return np.mean(vecs, axis=0)


In [38]:

x_train_w2v = np.vstack([doc_vector_avg(t, wv, DIM) for t in x_train_tokens])
x_test_w2v  = np.vstack([doc_vector_avg(t, wv, DIM) for t in x_test_tokens])


In [39]:
x_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9600, 36014))

In [40]:
x_train_w2v

array([[ 0.07080935,  0.03319945, -0.00946214, ..., -0.05757089,
         0.00335213,  0.00456732],
       [ 0.07390501,  0.01170001, -0.03076279, ..., -0.04758279,
         0.02257184,  0.00314893],
       [ 0.05621754,  0.01476417, -0.01157369, ..., -0.04956292,
         0.01509401,  0.0023885 ],
       ...,
       [ 0.05027262,  0.08076986,  0.04113092, ..., -0.06608073,
         0.02255334, -0.065389  ],
       [ 0.06565285, -0.03878021,  0.00557327, ..., -0.06098366,
        -0.05310392,  0.06922579],
       [ 0.08752441, -0.02451869, -0.15452358, ..., -0.06343297,
         0.03856441,  0.00640869]], shape=(9600, 300), dtype=float32)

In [41]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(x_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(x_train_tfidf,y_train)
nb_model_w2v = GaussianNB().fit(x_train_w2v,y_train)

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [48]:
y_pred_w2v = nb_model_w2v.predict(x_test_w2v)

In [46]:
confusion_matrix(y_test, y_pred_w2v)

array([[ 669,  160],
       [ 484, 1087]])

In [47]:
print("w2v accuracy: ",accuracy_score(y_test,y_pred_w2v))

w2v accuracy:  0.7316666666666667
